In [4]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.datasets import load_iris


In [47]:
#recuperatio_dataset
base=load_iris()
X=base.data
Y=base.target

In [48]:
#visualisatio_des_data
import matplotlib.pyplot as plt
#plt.scatter(X[:,2],X[:,3])

In [49]:
#visualisatio_des_data_echelle
scaler=MinMaxScaler()
X_trans=scaler.fit_transform(X)
#plt.scatter(X_trans[:,2],X_trans[:,3])
#print(X_trans)



In [17]:
import numpy as np
print(np.var(X_trans))

0.06883657369709498


In [18]:
from sklearn.preprocessing import StandardScaler

In [ ]:
from sklearn.preprocessing import StandardScaler
#visualisatio_des_normalisations_standard
scaler1= StandardScaler()
X_trans1=scaler1.fit_transform(X)

In [50]:
#visualisatio_des_normalisations_standard
scaler1= StandardScaler()
X_trans1=scaler1.fit_transform(X)
#print(X_trans1)

In [20]:
import numpy as np
print(np.var(X_trans1))

1.0


In [21]:
from sklearn.preprocessing import RobustScaler

In [78]:
#visualisatio_des_Normalisations robustes
from sklearn.preprocessing import RobustScaler
scaler2= RobustScaler()
X_trans2=scaler2.fit_transform(X)
print(X_trans2)

[[-0.53846154  1.         -0.84285714 -0.73333333]
 [-0.69230769  0.         -0.84285714 -0.73333333]
 [-0.84615385  0.4        -0.87142857 -0.73333333]
 [-0.92307692  0.2        -0.81428571 -0.73333333]
 [-0.61538462  1.2        -0.84285714 -0.73333333]
 [-0.30769231  1.8        -0.75714286 -0.6       ]
 [-0.92307692  0.8        -0.84285714 -0.66666667]
 [-0.61538462  0.8        -0.81428571 -0.73333333]
 [-1.07692308 -0.2        -0.84285714 -0.73333333]
 [-0.69230769  0.2        -0.81428571 -0.8       ]
 [-0.30769231  1.4        -0.81428571 -0.73333333]
 [-0.76923077  0.8        -0.78571429 -0.73333333]
 [-0.76923077  0.         -0.84285714 -0.8       ]
 [-1.15384615  0.         -0.92857143 -0.8       ]
 [ 0.          2.         -0.9        -0.73333333]
 [-0.07692308  2.8        -0.81428571 -0.6       ]
 [-0.30769231  1.8        -0.87142857 -0.6       ]
 [-0.53846154  1.         -0.84285714 -0.66666667]
 [-0.07692308  1.6        -0.75714286 -0.66666667]
 [-0.53846154  1.6        -0.81

In [23]:
import numpy as np
print(np.var(X_trans2))

0.4281264074685319


In [ ]:
scaler=MinMaxScaler()
X_trans=scaler.fit_transform(X)
print(X_trans)

In [71]:
from sklearn.preprocessing import PowerTransformer

In [53]:
#visualisatio_des_normalisation transformpower
from sklearn.preprocessing import PowerTransformer
scaler4= PowerTransformer()
X_trans4=PowerTransformer().fit_transform(X)
#print(X_trans4)
#plt.scatter(X_trans4[:,2],X_trans4[:,3])

In [39]:
import numpy as np
print(np.var(X_trans4))

1.0000000000000002


In [65]:
#Normalisation au vecteur unitaire
import numpy as np
X_trans5= X / np.sqrt(np.sum(X**2))
#print(X_trans5)
#plt.scatter(X_trans5[:,2],X_trans5[:,3])

In [46]:
import numpy as np
print(np.var(X_trans5))

0.0004084220541221272


In [66]:
from sklearn import preprocessing
X_trans3 = preprocessing.normalize(X)
#print(X_trans3)

#scaled_df = pd.DataFrame(d, columns=names)
#scaled_df.head()

In [67]:
import numpy as np
print(np.var(X_trans3))

0.058061926380652336


In [72]:
from sklearn.preprocessing import MaxAbsScaler

In [80]:
#visualisatio_des_Normalisations MaxAbsScaler ou Robuste
from sklearn.preprocessing import MaxAbsScaler
scaler6= MaxAbsScaler()
X_trans6=scaler2.fit_transform(X)
#print(X_trans6)

In [75]:
import numpy as np
print(np.var(X_trans6))

0.4281264074685319
